#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cwchar>
#include <memory>
#include <wrl/client.h>
#include <windows.h>
#include <d3d11_4.h>
#include <d2d1_3.h>
#include <d2d1_3helper.h>
#include <dwrite_3.h>
#include <shellscalingapi.h>
#include <dwmapi.h>
#include <imm.h>
#include "third_party/mpack/mpack.h"
#include "common/dx_helper.h"
#include "common/mpack_helper.h"
#include "common/vec.h"
#include "common/window_messages.h"
using Microsoft::WRL::ComPtr;